[package]
name = "audio-limiter"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.30"
cpal = "0.15"
ringbuf = "0.4"
atomic_float = "1.1.0"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
